[package]
name = "hah-dsl"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
hah-core = { path = "../hah-core" }
hah-utils = { path = "../hah-utils" }
anyhow = "1"
regex = "1"
serde = { version = "1", features = ["derive"] }
winnow = "1.0.3"

[dev-dependencies]
hah-core = { path = "../hah-core", features = ["mock"] }
mockall = { workspace = true }
tempfile = "3"
