#!/usr/bin/env python3
"""Generate DEPENDENCIES.md from cargo metadata.

Writes to stdout; redirect to DEPENDENCIES.md:

    python3 tools/gen_deps_doc.py > DEPENDENCIES.md

or via the Makefile target:

    make doc-dependencies
"""

import json
import subprocess
import sys
from collections import defaultdict


def req_display(req: str) -> str:
    """Convert a cargo version requirement to a short display string.

    '^0.9.35' -> '0.9', '^1' -> '1', '^0.0.12' -> '0.0'
    """
    s = req.lstrip("^~=>< ")
    # Drop any trailing comma-separated constraints (e.g. ">=1.0, <2.0")
    s = s.split(",")[0].strip()
    parts = s.split(".")
    if parts[0] == "0" and len(parts) >= 2:
        return f"0.{parts[1]}"
    return parts[0]


def main() -> None:
    meta = json.loads(
        subprocess.check_output(
            ["cargo", "metadata", "--format-version", "1"],
            stderr=subprocess.DEVNULL,
        )
    )

    workspace_member_ids: set[str] = set(meta["workspace_members"])
    pkgs_by_id: dict[str, dict] = {p["id"]: p for p in meta["packages"]}
    workspace_names: set[str] = {pkgs_by_id[wid]["name"] for wid in workspace_member_ids}

    # Which deps are declared optional in each workspace member
    optional_in: dict[str, set[str]] = {}
    req_in: dict[str, dict[str, str]] = {}
    for wid in workspace_member_ids:
        pkg = pkgs_by_id[wid]
        wm_name = pkg["name"]
        optional_in[wm_name] = {d["name"] for d in pkg["dependencies"] if d.get("optional", False)}
        req_in[wm_name] = {d["name"]: d["req"] for d in pkg["dependencies"]}

    # Collect direct external deps across all workspace members.
    # A dep is "runtime" if it appears as kind=None (normal) AND is NOT optional
    # in the declaring member. Everything else is "dev-only".
    direct: dict[str, dict] = {}

    for node in meta["resolve"]["nodes"]:
        if node["id"] not in workspace_member_ids:
            continue
        wm_name = pkgs_by_id[node["id"]]["name"]

        for dep in node["deps"]:
            dep_pkg = pkgs_by_id[dep["pkg"]]
            dep_name = dep_pkg["name"]
            if dep_name in workspace_names:
                continue  # skip internal workspace crates

            if dep_name not in direct:
                direct[dep_name] = {
                    "runtime": False,
                    "req": req_in[wm_name].get(dep_name, "?"),
                    "pkg": dep_pkg,
                }

            for kind_info in dep["dep_kinds"]:
                if kind_info["kind"] is None and dep_name not in optional_in[wm_name]:
                    direct[dep_name]["runtime"] = True

    runtime = sorted(
        [(n, d) for n, d in direct.items() if d["runtime"]],
        key=lambda x: x[0].lower(),
    )
    dev_only = sorted(
        [(n, d) for n, d in direct.items() if not d["runtime"]],
        key=lambda x: x[0].lower(),
    )

    def row(name: str, info: dict) -> str:
        pkg = info["pkg"]
        ver = req_display(info["req"])
        lic = (pkg.get("license") or "unknown").strip()
        desc = (pkg.get("description") or "").strip().rstrip(".")
        url = f"https://crates.io/crates/{name}"
        return f"| [{name}]({url}) | {ver} | {lic} | {desc} |"

    col_header = "| Crate | Version | License | Purpose |\n| ----- | ------- | ------- | ------- |"

    lines = [
        "# Dependencies",
        "",
        "Direct dependencies of the HaH workspace crates.",
        "_Generated by `make doc-dependencies` — do not edit by hand._",
        "",
        "## Runtime Dependencies",
        "",
        col_header,
    ]
    for name, info in runtime:
        lines.append(row(name, info))

    lines += [
        "",
        "## Development-only Dependencies",
        "",
        col_header,
    ]
    for name, info in dev_only:
        lines.append(row(name, info))

    lines.append("")
    sys.stdout.write("\n".join(lines))


if __name__ == "__main__":
    main()
